# fly.toml app configuration file generated for axiom-logger on 2024-10-28T11:00:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'axiom-logger'
primary_region = 'mia'

[build]

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
